#!/bin/sh

mkdir -p /nginx_logs
mkdir -p /nginx_master/servers
mkdir -p /nginx_master/certs

echo "Starting Nginx ..."
nginx
if [ $? -ne 0 ]; then
    echo "Failed to start Nginx ..."
else
    echo "Nginx running ..."
fi

while true; do
    echo "Starting NginxMaster ..."
    /nginx_master_app
    EXIT_CODE=$?
    echo "NginxMaster exited with code $EXIT_CODE, Restarting in 1 second..."
    sleep 1
done
